### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by meyverick** [jollyroger-1989/multisolverr#1]
Sorry, newbie questions here.

Except for Flaresolverr, does it requires specific containers or does it works out of the box? I mean, it only requires a Scrappey API key and Flaresolverr URL?

Does it requires Flaresolverr:latest? I'm currently using Flaresolverr 1282.

**Comment by jollyroger-1989** [comment]
Hello.

It requires any Flaresolverr version as long as the api is the same as the official one. 

It also requires an http proxy. I recommend you to use squid. You'll find a lot of tutorials online to configure it with docker or directly on your system.
